name: Chrome

on: push

jobs:
  yarn-modern-pnp:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Chrome
        uses: cypress-io/github-action@v5
        timeout-minutes: 10
        with:
          install-command: yarn install
          start: yarn run start
          command: yarn run --binaries-only cypress run

  yarn-modern-pnp-no-server:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Chrome
        uses: cypress-io/github-action@v5
        timeout-minutes: 10
        with:
          install-command: yarn install
          command: yarn run --binaries-only cypress run
