name: Chrome

on: [push, workflow_dispatch]

env:
  CYPRESS_CACHE_FOLDER: $HOME/.cache/Cypress
  DEBUG: 'cypress:cli*'

jobs:
  chrome:
    runs-on: windows-11-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      # - name: Chrome install
      #   uses: browser-actions/setup-chrome@v1
      # fails: Error: Unsupported platform "windows" "arm64"
      - name: Edge install
        uses: browser-actions/setup-edge@v1
      # - name: Firefox install
      #   uses: browser-actions/setup-firefox@v1
      # fails: Error: Unsupported platform windows arm64 for version latest
      - name: Show runner infos
        run: |
          node -p "'OS type:     ' + os.type()"
          node -p "'OS version:  ' + os.version()"
          node -p "'OS release:  ' + os.release()"
          node -p "'OS platform: ' + os.platform()"
          node -p "'OS arch:     ' + os.arch()"
          node -p "'OS machine:  ' + os.machine()"
          echo "OS cpus:"
          node -p "os.cpus()"
      - name: Install dependencies
        run: npm ci
        env:
          CYPRESS_INSTALL_BINARY: 0 # do not install Cypress binary
      - name: Install Cypress binary
        run: npx cypress install
      - name: List Cypress cache folder
        run: npx cypress cache list
      - name: Verify Cypress install
        run: npx cypress verify
      - name: Show Cypress version
        run: npx cypress version
      - name: Show installed browsers
        run: npx cypress info
      - name: Cypress test with Chrome
        uses: cypress-io/github-action@v6
        timeout-minutes: 10
        with:
          build: npm run build
          start: npm start
          browser: chrome
          install: false
