# This is a test workflow which is not part of the production repository

name: Cypress Tests

on: [push, workflow_dispatch]

jobs:
  # cypress-run:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     # Install NPM dependencies, cache them correctly
  #     # and run all Cypress tests
  #     - name: Cypress run
  #       uses: cypress-io/github-action@v6
  #       with:
  #         build: npm run build
  #         start: npm start
  show-owner:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_REPOSITORY
      - run: echo $GITHUB_REPOSITORY_OWNER
