# Note: make sure to use the same version of cypress-io/github-action
# in all jobs, otherwise the last version wins I believe
name: Using Cypress GH Action

on: [push, workflow_dispatch]

jobs:
  single-run:
    name: every OS
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-24.04', 'windows-latest', 'macos-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: run tests
        uses: cypress-io/github-action@v6
        timeout-minutes: 10
        with:
          start: npm start
          # but for this particular project on Windows we need a different start command
          start-windows: npm run start
